/// Python ↔ Dart engine parity.
///
/// Loads test/fixtures/engine_vectors.json (generated by
/// python_lab/make_test_vectors.py) and asserts the Dart engine produces
/// identical outputs: exact for labels/indices, ±0.5 for angles/scores.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:rallycoach/core/engine/cue_prioritizer.dart';
import 'package:rallycoach/core/engine/engine_types.dart';
import 'package:rallycoach/core/engine/footwork.dart';
import 'package:rallycoach/core/engine/normalizer.dart';
import 'package:rallycoach/core/engine/phase_segmenter.dart';
import 'package:rallycoach/core/engine/shot_detector.dart';
import 'package:rallycoach/core/engine/technique_scorer.dart';

List<List<double>> _kp(dynamic raw) => [
      for (final p in raw as List)
        [for (final v in p as List) (v as num).toDouble()],
    ];

({List<TimedKeypoints> frames, Map<String, int> viewCounts, List<double> torsos})
    _normalizeStream(List rawFrames) {
  final frames = <TimedKeypoints>[];
  final viewCounts = <String, int>{};
  final torsos = <double>[];
  for (final f in rawFrames) {
    final n = normalizeFrame(f['t'] as int, _kp(f['kp']));
    if (n == null) continue;
    frames.add(TimedKeypoints(
        timestampMs: n.timestampMs, keypoints: n.keypoints));
    viewCounts[n.view.id] = (viewCounts[n.view.id] ?? 0) + 1;
    torsos.add(n.torso);
  }
  return (frames: frames, viewCounts: viewCounts, torsos: torsos);
}

String _majorityView(Map<String, int> counts) {
  // Python's max() keeps the first key with the max value in insertion
  // order; Map iteration order in Dart matches insertion order too.
  String? best;
  var bestCount = -1;
  counts.forEach((k, v) {
    if (v > bestCount) {
      bestCount = v;
      best = k;
    }
  });
  return best!;
}

void main() {
  final vectors = jsonDecode(
          File('test/fixtures/engine_vectors.json').readAsStringSync())
      as Map<String, dynamic>;

  group('unit vectors', () {
    test('normalize_frame + joint_angles', () {
      for (final sample in vectors['unit']['normalize_samples'] as List) {
        final expected = sample['expected'] as Map<String, dynamic>;
        final n = normalizeFrame(0, _kp(sample['kp']))!;
        expect(n.view.id, expected['view']);
        expect(n.torso, closeTo((expected['torso'] as num).toDouble(), 0.01));
        expect(n.shoulderWidthRatio,
            closeTo((expected['shoulder_width_ratio'] as num).toDouble(), 0.01));
        final angles = jointAngles(n.keypoints);
        final exp = expected['angles'] as Map<String, dynamic>;
        expect(angles.elbowAngle,
            closeTo((exp['elbow_angle'] as num).toDouble(), 0.5));
        expect(angles.kneeFlexion,
            closeTo((exp['knee_flexion'] as num).toDouble(), 0.5));
        expect(angles.trunkTilt,
            closeTo((exp['trunk_tilt'] as num).toDouble(), 0.5));
        expect(angles.shoulderLineDeg,
            closeTo((exp['shoulder_line_deg'] as num).toDouble(), 0.5));
        expect(angles.hipLineDeg,
            closeTo((exp['hip_line_deg'] as num).toDouble(), 0.5));
        expect(angles.wristX, closeTo((exp['wrist_x'] as num).toDouble(), 0.01));
        expect(angles.wristY, closeTo((exp['wrist_y'] as num).toDouble(), 0.01));
      }
    });

    test('score_metric edge cases', () {
      for (final c in vectors['unit']['score_metric_cases'] as List) {
        final got = scoreMetric(
          (c['value'] as num).toDouble(),
          [for (final v in c['ideal'] as List) (v as num).toDouble()],
          (c['tolerance'] as num?)?.toDouble(),
        );
        expect(got, closeTo((c['expected'] as num).toDouble(), 0.01));
      }
    });

    test('mirror_normalized', () {
      final input = [
        for (final p in vectors['unit']['mirror_input'] as List)
          [for (final v in p as List) (v as num).toDouble()],
      ];
      final got = mirrorNormalized(input);
      final exp = vectors['unit']['mirror_expected'] as List;
      for (var i = 0; i < Kp.count; i++) {
        expect(got[i][0], closeTo(((exp[i] as List)[0] as num).toDouble(), 0.001));
        expect(got[i][1], closeTo(((exp[i] as List)[1] as num).toDouble(), 0.001));
      }
    });

    test('pick_cue', () {
      final c = vectors['unit']['cue_case'] as Map<String, dynamic>;
      final deviations = [
        for (final d in c['deviations'] as List)
          MetricDeviation(
            phase: 'contact',
            id: d['id'] as String,
            value: 0,
            ideal: const [0, 1],
            direction: 'low',
            severity: (d['severity'] as num).toDouble(),
            weight: (d['weight'] as num).toDouble(),
            cue: '',
          ),
      ];
      final got = pickCue(
        deviations,
        {for (final r in c['recent'] as List) r as String},
        {
          for (final e in (c['recurrence'] as Map<String, dynamic>).entries)
            e.key: (e.value as num).toInt(),
        },
      );
      expect(got!.id, c['expected']);
    });
  });

  group('pipeline vectors', () {
    for (final rawCase in vectors['pipeline'] as List) {
      final c = rawCase as Map<String, dynamic>;
      test(c['name'], () {
        final expected = c['expected'] as Map<String, dynamic>;
        final stream = _normalizeStream(c['input_frames'] as List);
        expect(_majorityView(stream.viewCounts), expected['view']);

        final shots = detectShots(stream.frames);
        expect(shots.length, 1);
        final shot = shots.single;
        final expShot = expected['shot'] as Map<String, dynamic>;
        expect(shot.start, expShot['start']);
        expect(shot.peak, expShot['peak']);
        expect(shot.end, expShot['end']);
        expect(shot.peakSpeed,
            closeTo((expected['peak_speed'] as num).toDouble(), 0.05));

        final (stroke, classConf) = classifyShot(stream.frames, shot);
        expect(stroke.id, expected['stroke']);
        expect(classConf, greaterThan(0.0));

        final phases = segmentPhases(stream.frames, shot, stroke);
        final expPhases = expected['phases'] as Map<String, dynamic>;
        expect(phases.prep, expPhases['prep']);
        expect(phases.backswing, expPhases['backswing']);
        expect(phases.contact, expPhases['contact']);
        expect(phases.followEnd, expPhases['follow_end']);

        final address = jointAngles(stream.frames[shot.start].keypoints);
        final measured = measureMetrics(stream.frames, phases, address);
        final expMeasured = expected['measured'] as Map<String, dynamic>;
        expMeasured.forEach((phase, metrics) {
          (metrics as Map<String, dynamic>).forEach((id, value) {
            expect(measured[phase]![id]!,
                closeTo((value as num).toDouble(), 0.5),
                reason: '$phase.$id');
          });
        });

        final refJson = jsonDecode(File(
                'assets/reference/${expected['stroke']}.json')
            .readAsStringSync()) as Map<String, dynamic>;
        final reference = StrokeReference.fromJson(
            refJson['skill_levels'][c['tier']] as Map<String, dynamic>);
        final scored = scoreShot(
            measured, reference, ViewBucket.fromId(expected['view'] as String));
        expect(scored.score, closeTo((expected['score'] as num).toDouble(), 0.5));
        final expPhaseScores = expected['phase_scores'] as Map<String, dynamic>;
        expPhaseScores.forEach((phase, value) {
          expect(scored.phaseScores[phase]!,
              closeTo((value as num).toDouble(), 0.5),
              reason: 'phase_score.$phase');
        });
        expect([for (final d in scored.deviations) d.id],
            expected['deviation_ids']);
        if (expected['top_deviation'] != null) {
          expect(scored.deviations.first.id, expected['top_deviation']);
        }
      });
    }
  });

  test('footwork window parity', () {
    final fw = vectors['footwork'] as Map<String, dynamic>;
    final stream = _normalizeStream(fw['input_frames'] as List);
    final rawHipX = [for (final x in fw['raw_hip_x'] as List) (x as num).toDouble()];
    final got = analyzeFootworkWindow(
        stream.frames, rawHipX, (fw['torso'] as num).toDouble());
    final exp = fw['expected'] as Map<String, dynamic>;
    expect(got.splitStepRate,
        closeTo((exp['split_step_rate'] as num).toDouble(), 0.01));
    expect(got.stanceWidth,
        closeTo((exp['stance_width'] as num).toDouble(), 0.01));
    expect(got.recoverySteps,
        closeTo((exp['recovery_steps'] as num).toDouble(), 0.01));
  });
}
